# Generated by Django 5.0 on 2024-03-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opiekunki_app', '0002_opiekunka_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='opiekunka',
            old_name='opis',
            new_name='miasto',
        ),
        migrations.AddField(
            model_name='opiekunka',
            name='plec',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opiekunka',
            name='wiek',
            field=models.IntegerField(default=50),
        ),
    ]
