# Generated by Django 5.0 on 2024-03-13 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opiekunki_app', '0003_plec_rename_opis_opiekunka_miasto_opiekunka_plec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opiekunka',
            name='plec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opiekunki_app.plec'),
        ),
    ]
