# Generated by Django 5.0 on 2024-03-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opiekunki_app', '0004_alter_opiekunka_plec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opiekunka',
            name='miasto',
            field=models.CharField(max_length=100),
        ),
    ]
