# Generated by Django 5.0 on 2024-03-15 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opiekunki_app', '0006_rodzaj'),
    ]

    operations = [
        migrations.AddField(
            model_name='opiekunka',
            name='rodzaj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opiekunki_app.rodzaj'),
            preserve_default=False,
        ),
    ]
