# Generated by Django 5.0 on 2024-03-16 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opiekunki_app', '0007_opiekunka_rodzaj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('opiekunka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opiekunki_app.opiekunka')),
            ],
        ),
    ]
