# Generated by Django 5.0 on 2024-03-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opiekunki_app', '0008_opinia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinia',
            old_name='tresc',
            new_name='treść',
        ),
        migrations.RemoveField(
            model_name='opinia',
            name='data_dodania',
        ),
        migrations.AddField(
            model_name='opinia',
            name='autor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opinia',
            name='ocena',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
