# Generated by Django 5.0 on 2024-03-16 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opiekunki_app', '0009_rename_tresc_opinia_treść_remove_opinia_data_dodania_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinia',
            old_name='treść',
            new_name='tresc',
        ),
    ]
