# Generated by Django 5.0 on 2024-03-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opiekunki_app', '0013_alter_opinia_ocena'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinia',
            old_name='autor',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='opiekunka',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
