# Generated by Django 5.0 on 2024-03-18 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opiekunki_app', '0014_rename_autor_opinia_user_alter_opiekunka_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinia',
            name='ocena',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
