# Generated by Django 5.0 on 2024-03-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opiekunki_app', '0015_alter_opinia_ocena'),
    ]

    operations = [
        migrations.AddField(
            model_name='opiekunka',
            name='opis',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
